### PR TITLE
Used topic template for python sample

### PR DESCRIPTION
**Pull request by munir131**

### CODE REVIEW

**Review by tapanbavaliya — APPROVED** [review]
LGTM

**Review by deonvdv — APPROVED** [review]
LGTM

**Review by deltasquare4 — APPROVED** [review]

**Comment by deltasquare4** [comment]
@munir131 Can you please rebase this branch on top of `develop` and edit this PR base to it? There are a lot of other change when I changed the PR base.

**Comment by munir131** [comment]
@deltasquare4 Done

**Pull request merged**
